version: '2'
services:
  hitchhiker:
    image: hitchhiker
    container_name: hitchhiker
    environment:
      - HITCHHIKER_DB_HOST=hitchhiker-mysql
    ports:
      - "8080:8080"
      - "11010:11010"
    volumes:
      - /my/hitchhiker/public:/usr/src/Hitchhiker/build/public
      - /my/hitchhiker/data:/usr/src/Hitchhiker/build/global_data/project
      - /my/hitchhiker/backup:/usr/src/Hitchhiker/build/backup
      - /my/hitchhiker/logs:/usr/src/Hitchhiker/build/logs
    links:
      - hitchhiker-mysql
  hitchhiker-mysql:
    image: mysql:5.7
    container_name: hitchhiker-mysql
    environment:
      - MYSQL_DATABASE=hitchhiker
    volumes:
      - ./hitchhiker.conf:/etc/mysql/conf.d/hitchhiker.conf
      - /my/hitchhiker/sqldata:/var/lib/mysql